version: '3.7'

services:
  hello-world:
    container_name: hello-world
    build:
      context: $PRODUCT_DIR/packages/_hello-world
      dockerfile: dev.Dockerfile
    depends_on:
      - nginx
    init: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: $PRODUCT_DIR/packages/_hello-world
        target: /usr/src/app
    domainname: hello-world
    hostname: hello-world
    expose:
      - '8000'
    networks:
      product_network:
        aliases:
          - hello-world.anoriqq.local
    env_file:
      - $PRODUCT_DIR/packages/_hello-world/secret/local.env
    command: yarn debug

  nginx:
    container_name: nginx
    image: nginx:1.17.5-alpine
    tty: true
    restart: always
    volumes:
      - type: bind
        source: $PRODUCT_DIR/packages/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: $PRODUCT_DIR/packages/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: $PRODUCT_DIR/packages/nginx/certs
        target: /etc/nginx/certs
    domainname: product.anoriqq.local
    hostname: product.anoriqq.local
    expose:
      - '80'
      - '443'
    ports:
      - '80:80'
      - '443:443'
    networks:
      product_network:
        aliases:
          - anoriqq.local
          - product.anoriqq.local

  redis:
    container_name: redis
    image: redis:6.0-rc1-alpine
    tty: true
    restart: always
    volumes:
      - $PRODUCT_DIR/packages/redis/data:/data
    domainname: redis
    hostname: redis
    expose:
      - '6379'
    networks:
      product_network:
    # env_file:
    #   - $PRODUCT_DIR/packages/redis/.env

  mongodb:
    container_name: mongodb
    image: mongo:4.2.1-bionic
    tty: true
    restart: always
    volumes:
      - $PRODUCT_DIR/packages/mongodb/db:/data/db
      - $PRODUCT_DIR/packages/mongodb/mongod.conf:/etc/mongod.conf
    domainname: mongodb
    hostname: mongodb
    expose:
      - '27017'
    ports:
      - '27017:27017' # For debug
    networks:
      product_network:
    # env_file:
    #   - $PRODUCT_DIR/packages/mongodb/.env

  mongodb-runner:
    container_name: mongodb-runner
    image: mongo:4.2.1-bionic
    depends_on:
      - mongodb
    tty: true
    volumes:
      - $PRODUCT_DIR/packages/mongodb/createMongodbUser.js:/createMongodbUser.js
    domainname: mongodb-runner
    hostname: mongodb-runner
    networks:
      product_network:
    # env_file:
    #   - $PRODUCT_DIR/packages/mongodb/.env
    command: mongo --host mongodb --port 27017  --authenticationDatabase "admin" -u "admin-user" -p "admin-password" /createMongodbUser.js

  portfolio:
    container_name: portfolio
    build:
      context: $PRODUCT_DIR/packages/portfolio
    depends_on:
      - nginx
    init: true
    tty: true
    restart: always
    domainname: portfolio
    hostname: portfolio
    expose:
      - '8000'
    networks:
      product_network:
        aliases:
          - anoriqq.local
          - product.anoriqq.local

  delay-tweet:
    container_name: delay-tweet
    build:
      context: $PRODUCT_DIR/packages/delay-tweet
      dockerfile: dev.Dockerfile
    depends_on:
      - nginx
      - mongodb
    init: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: $PRODUCT_DIR/packages/delay-tweet
        target: /usr/src/app
    domainname: delay-tweet
    hostname: delay-tweet
    expose:
      - '8000'
    networks:
      product_network:
        aliases:
          - delay-tweet.anoriqq.local
    env_file:
      - $PRODUCT_DIR/packages/delay-tweet/secret/local.env
    command: yarn debug

  youtube-comments:
    container_name: youtube-comments
    build:
      context: $PRODUCT_DIR/packages/youtube-comments
      dockerfile: dev.Dockerfile
    depends_on:
      - nginx
      - mongodb-runner
      - redis
    init: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: $PRODUCT_DIR/packages/youtube-comments
        target: /usr/src/app
    domainname: youtube-comments
    hostname: youtube-comments
    expose:
      - '8000'
      - '3000'
    networks:
      product_network:
        aliases:
          - youtube-comments.anoriqq.local
    env_file:
      - $PRODUCT_DIR/packages/youtube-comments/secret/local.env

networks:
  product_network:
