version: '3.7'

services:
  nginx:
    image: nginx:1.17.5-alpine
    volumes:
      - type: bind
        source: ./packages/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./packages/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./packages/nginx/certs
        target: /etc/nginx/certs
    domainname: product.anoriqq.local
    hostname: product.anoriqq.local
    expose:
      - '80'
      - '443'
    ports:
      - '80:80'
      - '443:443'
    networks:
      app_net:
        aliases:
          - anoriqq.local
          - product.anoriqq.local

  portfolio:
    build:
      context: ./packages/portfolio
    init: true
    domainname: portfolio
    hostname: portfolio
    expose:
      - '8000'
    networks:
      app_net:
        aliases:
          - anoriqq.local
          - product.anoriqq.local

  delay-tweet:
    build:
      context: ./packages/delay-tweet
    init: true
    domainname: delay-tweet
    hostname: delay-tweet
    expose:
      - '8000'
    networks:
      app_net:
        aliases:
          - delay-tweet.anoriqq.local

networks:
  app_net:
