version: '3.7'

services:
  nginx:
    image: nginx:1.17.5-alpine
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./packages/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./packages/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./packages/nginx/certs
        target: /etc/nginx/certs
    domainname: product.anoriqq.local
    hostname: product.anoriqq.local
    expose:
      - '80'
      - '443'
    ports:
      - '80:80'
      - '443:443'
    networks:
      product_network:
        aliases:
          - anoriqq.local
          - product.anoriqq.local

  mongo:
    image: mongo:4.2.1-bionic
    tty: true
    restart: always
    volumes:
      - ./packages/mongo/db:/data/db
      # - ./packages/mongo/configdb:/data/configdb
    domainname: mongo
    hostname: mongo
    ports:
      - 27017:27017
    networks:
      product_network:
    env_file:
      - ./packages/mongo/.env

  portfolio:
    build:
      context: ./packages/portfolio
    init: true
    tty: true
    restart: always
    domainname: portfolio
    hostname: portfolio
    expose:
      - '8000'
    networks:
      product_network:
        aliases:
          - anoriqq.local
          - product.anoriqq.local

  delay-tweet:
    build:
      context: ./packages/delay-tweet
    init: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./packages/delay-tweet
        target: /usr/src/app
    domainname: delay-tweet
    hostname: delay-tweet
    expose:
      - '8000'
    networks:
      product_network:
        aliases:
          - delay-tweet.anoriqq.local
    env_file:
      - ./packages/delay-tweet/.env
    command: yarn debug

networks:
  product_network:
